version: '3'

services:
  client:
    build:
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    image: julianmedwards/react-trello-app:dev
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - 3001:5173
    volumes:
      - ./trello-react-app:/usr/src/app
      - /usr/src/app/node_modules/
  db:
    image: julianmedwards/trello-mysql-db:dev
  api:
    build:
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    image: julianmedwards/trello-api-sql:dev
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./trello-api-sql:/usr/src/api
      - /usr/src/api/node_modules/
