version: '3'

services:
  client:
    build:
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - PORT=3000
    image: julianmedwards/react-trello-app:prod
    ports:
      - 3000:3000
  db:
    image: julianmedwards/trello-mysql-db:prod
  api:
    build:
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: julianmedwards/trello-api-sql:prod
