version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
    healthcheck:
      test: 'mysqladmin ping -P 3306 -proot || exit 1'
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT_ALIAS}:${MYSQL_PORT}
    networks:
      - localnetwork
  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./trello-api-sql
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
    deploy:
      restart_policy:
        condition: on-failure
    working_dir: /usr/src/api
    environment:
      NODE_ENV: production
      API_PORT: ${API_PORT_PROD}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_HOST: ${MYSQL_HOST}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_PORT: ${MYSQL_PORT}
    ports:
      - ${API_PORT_PROD}:${API_PORT_PROD}
    networks:
      - localnetwork

networks:
  localnetwork:
