version: '3'

services:
  db:
    image: julianmedwards/trello-mysql-db:prod
  api:
    build:
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: julianmedwards/trello-api-sql:prod
