version: '3'

services:
  client:
    build:
      context: ./trello-react-app
      dockerfile: Dockerfile.dev
      args:
        - NODE_VERSION=${NODE_VERSION}
        - NODE_ENV=development
    image: julianmedwards/react-trello-app:dev
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - 3001:5173
    working_dir: /usr/src/app
    volumes:
      - ./trello-react-app:/usr/src/app
      - /usr/src/app/node_modules/
    networks:
      - localnetwork
  db:
    image: julianmedwards/trello-mysql-db:dev
  api:
    build:
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    image: julianmedwards/trello-api-sql:dev
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./trello-api-sql:/usr/src/api
      - /usr/src/api/node_modules/
